### ISSUE TITLE
multiprocessing.pool.MaybeEncodingError

### ISSUE THREAD

**Issue by BramVanroy** [cgnorthcutt/hypopt#11]
I am getting the follow error trace while optimising a RFR, Ubuntu Python 3.6.4.

```bash
Traceback (most recent call last):
  File "main.py", line 177, in <module>
    model_test_path, save_predictions_path, args.classifier, args.criterion, args.num_threads, args.relu, args.verbose)
  File "main.py", line 128, in main
    model = train_model(train_p, val_p, gs_p, clfr, criterion, num_threads, verbose)
  File "main.py", line 74, in train_model
    model = gs.fit(X_train, y_train, X_val, y_val, scoring='neg_mean_squared_error', verbose=verbose)
  File "/home/bram/.local/share/virtualenvs/dpc_cross_ml-DMx7zq90/lib/python3.6/site-packages/hypopt/model_selection.py", line 289, in fit
    results = _parallel_param_opt(jobs, threads = self.num_threads)
  File "/home/bram/.local/share/virtualenvs/dpc_cross_ml-DMx7zq90/lib/python3.6/site-packages/hypopt/model_selection.py", line 146, in _parallel_param_opt
    results = pool.map(_run_thread_job, lst)
  File "/home/bram/.pyenv/versions/3.6.4/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/bram/.pyenv/versions/3.6.4/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[(RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=500,
                      n_jobs=None, oob_score=False, random_state=0,
                      verbose=True, warm_start=False), -1.4925891438469021)]'. Reason: 'error("'i' format requires -2147483648 <= number <= 2147483647",)'
```

On Windows, Python 3.7.1, the trace is a bit different.

```python
Traceback (most recent call last):
  File "c:\python\python37\Lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\python\python37\Lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python\python37\Lib\multiprocessing\pool.py", line 496, in _handle_results
    task = get()
  File "c:\python\python37\Lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "c:\python\python37\Lib\multiprocessing\connection.py", line 318, in _recv_bytes
    return self._get_more_data(ov, maxsize)
  File "c:\python\python37\Lib\multiprocessing\connection.py", line 337, in _get_more_data
    assert left > 0
AssertionError
```

From what I read, this is caused by the multiprocessing package having difficulties returning or pickling items bigger than 2GB. My output models would be around 5GB.

My code:

```python
# load_data() loads all data in memory from a given path
X_train, y_train = load_data(train_p)
X_train = StandardScaler().fit_transform(X_train)

X_val, y_val = load_data(val_p)
X_val = StandardScaler().fit_transform(X_val)

# load grid from some path. Here the contents are 4 values for n_estimators
with open(str(gs_p), encoding='utf-8') as fhin:
    param_grid = json.load(fhin)

gs = GridSearch(model=RandomForestRegressor(verbose=True), num_threads=24, param_grid=param_grid)
model = gs.fit(X_train, y_train, X_val, y_val, scoring='neg_mean_squared_error', verbose=True) # this line throws the error
```

Is there anything I can do to avoid this? Am I missing something?

**Comment by cgnorthcutt** [comment]
Thanks for sharing. Do you get the same issue with `sklearn.model_selection.GridSearch` ?

**Comment by BramVanroy** [comment]
Thanks for the quick reply.

Assuming you meant `GridSearchCV`: that one does work. The reason that I am using hypopt is, of course, that I wish to use a pre-defined validation set.

Maybe this is also important: using SVR instead RFR also _does_ work. Code (that works):

```python
# load_data() loads all data in memory from a given path
X_train, y_train = load_data(train_p)
X_train = StandardScaler().fit_transform(X_train)

X_val, y_val = load_data(val_p)
X_val = StandardScaler().fit_transform(X_val)

# load grid from some path. Here the contents are 4 values for n_estimators
with open(str(gs_p), encoding='utf-8') as fhin:
    param_grid = json.load(fhin)

gs = GridSearch(model=svm.SVR(verbose=True), num_threads=24, param_grid=param_grid)
model = gs.fit(X_train, y_train, X_val, y_val, scoring='neg_mean_squared_error', verbose=True)
```

This is odd to me, since the SVR models are much larger (~30GB for me). So why would the smaller RFR models cause an issue?

On second thought, maybe the size of the model is not the issue but the number of parameters/size of some list/a large object that cannot be pickled. For SVR all individual objects may be rather small, so that's no problem - but perhaps for RFR some objects are very large which leads to issues. Large could be in terms of memory and/or length of the object.

**Comment by cgnorthcutt** [comment]
Hi, so I created a minimum working example that works fine, but I'm running it on a much smaller dataset. Here it is

```python
import hypopt

# Import datasets, classifiers and performance metrics
from sklearn import datasets, svm, metrics
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# load_data() loads all data in memory from a given path
X_train = StandardScaler().fit_transform(X_train)
X_val = StandardScaler().fit_transform(X_val)

# Param grid for SVR
# param_grid = {
#     'C': [1, 10, 100, 120, 150],
#     'gamma': [0.001, 0.0001],
#     'kernel': ['rbf'],
# }

# Param grid for RandomForestRegressor
param_grid = {
    'n_estimators': [10, 20, 30, 40],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 3, 4],
}

gs = hypopt.GridSearch(model=RandomForestRegressor(verbose=True), num_threads=24, param_grid=param_grid)
model = gs.fit(X_train, y_train, X_val, y_val, scoring='neg_mean_squared_error', verbose=True)

print(gs.best_estimator_)
```

If you're issue is simply that the object is too large to be pickled with multi-processing (to my knowledge) there is no way around that without writing custom code to handle the dataset in chunks. I'll leave the thread open in case anyone from the community wants to chime in / potentially submit a PR to handle such situations.

**Comment by BramVanroy** [comment]
I'm not entirely sure what the problem is, but I would indeed guess that the size is the issue. This is rather strange because the data set is only ~120k samples large, and it works just fine for SVR. So I am not entirely sure what the issue with pickling a RFR model is. This does seem to be a problem of sklearn combined with multiprocessing (pickling the RFR model) rather than hypopt specifically, so perhaps this should be closed any way.

**Comment by cgnorthcutt** [comment]
Hi @BramVanroy . I fully rewrote all multiprocessing code. See: https://github.com/cgnorthcutt/hypopt/commit/e5fbbc5eb63f7499e0a5065cfee59b9de9fbaa79

Previously some models spun off child daemon processes that colluded with the parallelization processes. This is fixed now. I also added a parameter to `GridSearch(parallelization=True)`. You can run hypopt now without parallelization if its causing you issues. 

For more details on daemonic processes, check out this stack overflow link: https://stackoverflow.com/questions/6974695/python-process-pool-non-daemonic

Closing now. cheers.

**Comment by BramVanroy** [comment]
Tested, and it works. Thanks a lot for your work!

**Comment by cgnorthcutt** [comment]
Very glad to hear. Thanks for the update.

**Comment by BramVanroy** [comment]
Just to elaborate: running with parallelization a RFR still does not work, but without it does. Thanks for your time.
